features {
    'autoupdater',
    'ebtables-filter-multicast',
    'ebtables-filter-ra-dhcp',
    'ebtables-limit-arp',
    'mesh-batman-adv-15',
    'mesh-vpn-fastd',
    'respondd',
    'status-page',
    'web-advanced',
    'wireless-encryption-wpa3',
    'web-wizard',
}

packages {
    'gluon-mesh-batman-adv-15',
    'gluon-autoupdater',
    'gluon-config-mode-autoupdater',
    'gluon-config-mode-hostname',
    'gluon-config-mode-mesh-vpn',
    'gluon-config-mode-geo-location',
    'gluon-config-mode-contact-info',
    'gluon-config-mode-core',
    'gluon-ebtables-filter-multicast',
    'gluon-ebtables-filter-ra-dhcp',
    'gluon-web-admin',
    'gluon-web-autoupdater',
    'gluon-web-wifi-config',
    'gluon-web-private-wifi',
    'gluon-mesh-vpn-fastd',
    'gluon-radvd',
    'gluon-respondd',
    'gluon-setup-mode',
    'gluon-status-page',
    'gluon-ssid-changer',
    'respondd-module-airtime',
    'iwinfo',
}
